# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/crbonilha"

[social.params]
icon = "brand-github"

[[social]]
identifier = "codeforces"
name = "Codeforces"
url = "https://codeforces.com/profile/crbonilha"

[social.params]
icon = "code-forces"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/cristhian-bonilha-07359786/"

[social.params]
icon = "linkedin-social-media-svgrepo-com"
